Repository yupix/Mi.py, pull requests merged in 2021-12, with the labels that each got.

#51 Websockets to aiohttp
  .gitignore
  CHANGELOG.md
  README.md
  dist/mi.py-0.1.0-py3-none-any.whl
  dist/mi.py-0.1.0.tar.gz
  docs/_static/css/custom.css
  docs/mi.rst
  docs/requirements.txt
  mi/abc/ext/bot.py
  mi/chat.py
  mi/client.py
  mi/ext/commands/bot.py
  mi/gateway.py
  mi/http.py
  mi/instance.py
  mi/iterators.py
  mi/note.py
  mi/router.py
  mi/state.py
  mi/types/__init__.py
  mi/types/chat.py
  mi/types/note.py
  mi/types/user.py
  mi/user.py
  mi/utils.py
  requirements.txt
  setup.py
Labels: Extra Large

#67 Edited German translation
  docs/locale/de/LC_MESSAGES/index.po
  docs/locale/de/LC_MESSAGES/mi.po
Labels: Small

#72 V1.0.1
  CHANGELOG.md
  docs/conf.py
  docs/mi.rst
  mi/http.py
  mi/note.py
  mi/state.py
Labels: Small

#75 v1.0.2
  CHANGELOG.md
  mi/__init__.py
  mi/http.py
  mi/state.py
  mi/user.py
  setup.py
Labels: enhancement, Small

#76 fix: not working on_reaction event
  mi/state.py
Labels: Extra Small

#79 Feature/abolish pydantic
  .gitignore
  CHANGELOG.md
  docs/requirements.txt
  mi/client.py
  mi/drive.py
  mi/state.py
  mi/types/drive.py
  mi/types/user.py
  mi/user.py
  requirements.txt
  setup.py
Labels: Large
